version: '3'

services:

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  websocket-server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
